### ISSUE TITLE
URGENT: downgrade xz due to backdoor

### ISSUE THREAD

**Issue by gamer191** [strawberrymusicplayer/strawberry-macos-dependencies#189]
xz 5.6 and 5.6.1 contain a backdoor. See https://arstechnica.com/security/2024/03/backdoor-found-in-widely-used-linux-utility-breaks-encrypted-ssh-connections/, or just google "xz backdoor"

EDIT: this seems to also apply to most of @strawberrymusicplayer's other repos. I apologise if this was the wrong place to post it. I'm not gonna post this in the other repos (unless you ask me to), because I don't want to spam

**Comment by gamer191** [comment]
cc @jonaski

**Comment by jonaski** [comment]
Thanks, I'll revert the version since it has a backdoor. As far as I can tell, strawberry is not affected since you actually need to link the systems sshd to the compromised lzma lib, so this shouldn't directly affect any SSH on the macOS system, even if strawberry is installed, the latest strawberry version has xz 5.4.6 anyway. On Windows there is no SSH and we use CMake to build, and I believe only configure is affected.

**Comment by jonaski** [comment]
More details here: https://www.openwall.com/lists/oss-security/2024/03/29/4
